### ISSUE TITLE
Large inaccuracies near (but not on) triangle

### ISSUE THREAD

**Issue by alecjacobson** [zgimbutas/fmmlib3d#1]
Thank you so much for providing this library. So far I've had success with the particle dipoles, and I'm triangle to get dipoles on triangles working.

I'm running into an issue that I get large inaccuracies even for a just one double-sided triangle.

I'm calling the compiled fortran code from Matlab. In the following example I place a single unit-dipole-strength triangle along the yz-plane, then I compute the potential at grid locations on the xy-plane.

```
% Source triangle
VF = [0 0 0;-1 1 0;-0.2 -0.2 0.2];
N = [1 0 0];
C = mean(VF');
% Target grid
[X,Y] = meshgrid(linspace(-1,1),linspace(-1,1));
Z = zeros(size(X));
% Target positions
Q = [X(:) Y(:) Z(:)];

iprec = 3;
UFMM = lfmm3dtria(iprec,1,VF,N',C',0,0,1,1,N',0,0,size(Q,1),Q',1,0);
UDIR = l3dtriadirect   (1,VF,N',C',0,0,1,1,N',0,0,size(Q,1),Q',1,0);

UDIFF = real(UFMM.pottarg - UDIR.pottarg);
UREL = abs(UDIFF)./abs(UDIR.pottarg);
err_abs = max(abs(UDIFF))
err_rel = max(abs(UREL))
```

Running this, I see that the absolute and relative errors are quite large:

```
err_abs =
       1062.8
err_rel =
       312.11
```

If I visualize the direct solution (ground truth), I see what I expect:

![single-triangle-direct](https://user-images.githubusercontent.com/2241689/34390187-c24a375c-eb03-11e7-9de7-5e0416878d55.png)

If I visualize the fmm solution I see wild errors near the source triangle (cyan and yellow colors indicate out-of-range). Increasing the `iprec` option changes the error locations, but does not alleviate the problem (animation):

![single-triangle-fmm](https://user-images.githubusercontent.com/2241689/34390543-037bc5e0-eb06-11e7-8325-d680037498aa.gif)

I can also visualize the order of the error (log base 10 of absolute value) increasing `iprec` values, for the absolute error:

![single-triangle-absolute-error](https://user-images.githubusercontent.com/2241689/34390555-18e22168-eb06-11e7-839a-3ceb10eaa783.gif)

and the relative error:

![single-triangle-relative-error](https://user-images.githubusercontent.com/2241689/34390561-1dee0a78-eb06-11e7-947b-ea366d992b3f.gif)

The bottom left corner seems to really work correctly, but I'm not sure what's going on elsewhere.

Any chance I'm calling this function wrong? Or that there's a fix?

> Mac OS X 10.12, MATLAB r2018a, gfortran (gcc version 7.2.0)

**Comment by alecjacobson** [comment]
**Update:** I've confirmed that I get the same problem on Linux.

> Ubuntu 16.04.3, GNU Fortran (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609, MATLAB r2017a

**Comment by zgimbutas** [comment]
Hi, you are calling the function correctly, this is a known issue with
layer evaluation tools. For single or double layer density evaluation, the
FMM library has been designed to evaluate layer potentials on the surface
of somewhat uniformly discretized geometry and targets that are in the far
field (meaning at least one radius away for each triangle in
triangulation). This test hit the worst case scenario: the triangle is
locally big with respect of very fine target grid located very close to the
boundary. I checked the fmm oct-tree for this geometry, the source triangle
is located at the very edge of a large box inside oct-tree, leading to
large errors in formed multipole expansions.  This issue is not activated
in particle-target FMMs, since all points are automatically assigned to
correct computational boxes inside the oct-tree.

A possible fix would involve modifying the underlying FMM oct-tree, so that
it would be aware of source triangle radii, forcing direct evaluation for
nearby target points, and using some QBX FMM ideas to get robust high order
layer tools working.

A better fix that you can currently do (this has been tried by others,
because of lack of better tools and interface) is to write your own
high-order target evaluation routine as follows: first, replace the source
triangle densities with point discretizations by using a well-conditioned
interpolation/quadrature scheme (by either using the tensor-product Gauss
rule in src/triagauc.f or optimized nodes in src/triasymq.f), sort all
targets into the far-field and near-field targets, then, call the point FMM
for point-wise discretized geometry and far-field targets, and, finally,
evaluate the remaining interactions with near-field targets directly.

A quick workaround would be to refine the source geometry, making the
source triangles smaller and effectively pushing all targets further into
the far field with respect to the source geometry:

% Debugging output to screen and fort.13
fmm3dprini(6,13)

verts = [0 0 0;-1 1 0;-0.2 -0.2 0.2];
ifaces = [1 2 3]';
[verts,ifaces]=atrirefine(verts,ifaces);
[verts,ifaces]=atrirefine(verts,ifaces);
[verts,ifaces]=atrirefine(verts,ifaces);
[verts,ifaces]=atrirefine(verts,ifaces);

[triaflat,trianorm,triaarea,centroid,triatang1,triatang2] = ...
     atriproc(verts,ifaces);

% Source triangle
VF = triaflat;
N = trianorm;
C = centroid;

% Target grid
[X,Y] = meshgrid(linspace(-1,1),linspace(-1,1));
Z = zeros(size(X));
% Target positions
Q = [X(:) Y(:) Z(:)];

nsource = size(C,2);
charge = zeros(nsource);
dipstr = ones(nsource);

iprec = 3;
UFMM = lfmm3dtria(iprec,nsource,VF,N,C,0,0,1,dipstr,N,0,0,size(Q,1),Q',1,0);
UDIR = l3dtriadirect   (nsource,VF,N,C,0,0,1,dipstr,N,0,0,size(Q,1),Q',1,0);

UDIFF = real(UFMM.pottarg - UDIR.pottarg);
UREL = abs(UDIFF)./abs(UDIR.pottarg);
err_abs = max(abs(UDIFF))
err_rel = max(abs(UREL))

err = reshape(UDIR.pottarg - UFMM.pottarg, 100, 100);

err = reshape(UFMM.pottarg, 100, 100);
imagesc(log10(abs(err)))
colorbar

**Comment by alecjacobson** [comment]
Thanks. This response is super helpful. I'll try both immediate suggestions.

Is there a programmatic way to determine which targets are in the near / far field for a given: set of triangles, `iprec` value and set of targets?

I imagine I should compute closest distance from all targets over all triangles, but what is a safe radius? Will it depend on the aspect ratio of the triangles? Will it depend on the extend and spacing of the other target points?

**Comment by zgimbutas** [comment]
If you have a closed geometry, there is a nice trick involving double layer
potential with constant density to determine points close to the boundary:
the potential due a constant double layer density is 1 inside and 0 outside
the domain, and something else near the boundary. More accurate/correct way
involves hacking into the FMM tree structure and reading out the list of
targets inside so called List 1 of interaction boxes.

As for the second question. right now, some experimenting is needed to
determine the right parameters. I usually set the far field cutoff radius
to be about 2-3 source triangle radii, depending on precision.  I haven't
experimented with the aspect ratio and point distributions, but they do
matter in setting up the computational box structures, so the answer here
is likely to be yes.
