### ISSUE TITLE
Compiling examples with omp

### ISSUE THREAD

**Issue by ljg24** [zgimbutas/fmmlib3d#5]
Hi,
Thanks for making this code public, it is really useful. I have been trying to compile the 'lfmm3dpartdriver example code using OMP and whenever i run it, it gives me a segmentation fault (I tried increasing the stack size and it didnt help). When i dont use OMP it works fine. I tried using both gfortran compilers with the makefile flags, and ifort using -qopenmp -03. Let me know if you have any insight.

Luis

**Comment by zgimbutas** [comment]
Dear Luis, this is a known issue with the openmp stack size being set too small on your system.

Subject: test-openmp fmmlib2d broken / Mar 16, 2017

Dear Zydrunas,

[…]

1)
make test-openmp
creates ./int2 but segfaults, on two different modern linux systems
(EL7 w/ gcc 4.8.5 and ubuntu 16.04 LTS gcc 5.4.0)
I haven't fixed this.

[…]

Thanks,   Alex
*-------------------------------------------------------------------~-^`^-,.-'
|\   Dr Alex H. Barnett   Department of Mathematics, Dartmouth College.
| \                       Numerical Algorithms Group, Flatiron Institute.

Hi Alex,

[…]

1) I checked the release 1.2 on my CentOS 7 with gfortran 4.8.5 and macos with gfortran 5.3

make test-openmp is working fine on both systems. Something else is going on here.

In case openmp is misbehaving, I set my computers as following:

# omp default stack size is too small
export OMP_STACKSIZE=4096M
# no core dumps
ulimit -c 0
# unlimited stack
ulimit -s unlimited

[…]


Best,
Zydrunas


Dear Zydrunas,

You're right! That's the 3rd time I've been hit by openmp stacksize (due to static allocation in f77 test drivers!). make test-openmp now works.

[…]

Cheers, Alex


Under MacOS, linking with "-Wl,-stack_size,0x80000000”  should help with openmp stack size issues.

The fmmlib3d/contrib/ directory contains run_omp.sh script that you may find useful as well.

**Comment by ljg24** [comment]
Thank you for the quick reply. I will keep trying and try your suggestions. I found that the following works for my system for gfortran (I'm still trying to get intel compiler to work):
OBJSUF=o
MODSUF=mod
FC=gfortran -c 
FFLAGS=-O3 --openmp -fmax-stack-var-size=32768
FLINK=gfortran -o $(PROJECT) -O3 --openmp -fmax-stack-var-size=32768
Luis
